version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3200:80"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - spm-network

networks:
  spm-network:
    driver: bridge 